language: node_js
node_js:
  - 6
env:
- NODE_ENV=TEST
services:
  - mongodb
script:
  - cd nodeserver/loopback
  - npm install
  - npm start &
  - sleep 1
  - npm test
before_script:
  - sleep 1
