language: node_js
node_js:
  - 6
env:
- NODE_ENV=TEST
- EXPRESS_SESSION_SECRET=1234
services:
  - mongodb
script:
  - npm install
  - npm start &
  - sleep 1
  - npm test
before_script:
  - sleep 1
